global_config:
  total_epochs: 20
  batch_size: 4
  algorithm_type: grpo
model:
  model_path: '/PATH/TO/MODEL/CHECKPOINT/'
  max_prompt_tokens: 4096
  max_response_tokens: 16384
  checkpoint_path: 'checkpoints/WEBSHOP_RFT'
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: webshop
      storage_type: file
      path: 'scripts/data_prepare/webshop_data'
      format:
        prompt_key: 'task_id'
      rollout_args:
        repeat_times: 8
        temperature: 1.0
        logprobs: 0
    default_workflow_type: 'webshop_workflow'
  trainer_input:
    experience_buffer:
      name: webshop_buffer
      storage_type: queue
      path: 'sqlite:///webshop.db'
explorer:
  engine_type: vllm_async
  engine_num: 2
  runner_num: 8
  tensor_parallel_size: 2
  enable_prefix_caching: false
  enforce_eager: true
  dtype: bfloat16
  seed: 42
  use_ray: false
  backend: 'nccl'
  max_pending_requests: 32
  max_waiting_steps: 4
  gpu_memory_utilization: 0.7
  enable_chunked_prefill: true
synchronizer:
  sync_method: 'nccl'
  sync_interval: 8
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_webshop/train_webshop.yaml'
  save_interval: 10
monitor:
  cache_root_dir: ""
  project: "WEBSHOP"
  name: "WEBSHOP_RFT"
