project: "WEBSHOP"
name: "WEBSHOP_RFT"
algorithm_type: grpo
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
model:
  model_path: /PATH/TO/MODEL/
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 20
  batch_size: 4
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: webshop
      storage_type: file
      path: 'scripts/data_prepare/webshop_data'
      format:
        prompt_key: 'task_id'
      rollout_args:
        n: 8
        temperature: 1.0
        logprobs: 0
    default_workflow_type: 'webshop_workflow'
  trainer_input:
    experience_buffer:
      name: webshop_buffer
      storage_type: queue
      path: 'sqlite:///webshop.db'
explorer:
  runner_num: 8
  rollout_model:
    engine_type: vllm_async
    engine_num: 2
    tensor_parallel_size: 2
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    max_prompt_tokens: 4096
    max_response_tokens: 16384
    seed: 42
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
synchronizer:
  sync_method: 'nccl'
  sync_interval: 8
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_webshop/train_webshop.yaml'
  save_interval: 10
monitor:
  cache_root_dir: ""
