project: "ALFWORLD"
name: "ALFWORLD_RFT"
algorithm_type: grpo
checkpoint_root_dir: /PATH/TO/CHECKPOINT/ALFWORLD_RFT/
model:
  model_path: /PATH/TO/MODEL/
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 20
  batch_size: 4
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: alfworld
      storage_type: file
      path: 'scripts/data_prepare/alfworld_data'
      format:
        prompt_key: 'game_file'
      rollout_args:
        n: 8
        temperature: 1.0
        logprobs: 0
    default_workflow_type: 'alfworld_workflow'
  trainer_input:
    experience_buffer:
      name: alfworld_buffer
      storage_type: queue
      path: 'sqlite:///alfworld.db'
explorer:
  runner_num: 32
  rollout_model:
    engine_type: vllm_async
    engine_num: 2
    tensor_parallel_size: 2
    enable_prefix_caching: false
    enforce_eager: true
    max_prompt_tokens: 4096
    max_response_tokens: 16384
    dtype: bfloat16
    seed: 42
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
synchronizer:
  sync_method: 'nccl'
  sync_interval: 8
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_alfworld/train_alfworld.yaml'
  save_interval: 10
