mode: both
project: learn2ask
name: learn2ask_example
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: grpo
  repeat_times: 5
  sample_strategy: warmup
  policy_loss_fn: ppo
  advantage_fn: grpo
  kl_penalty_fn: none
  kl_loss_fn: k2
  entropy_loss_fn: default
data_processor: {}
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen3-8B}
  max_prompt_tokens: 2048
  max_response_tokens: 1024
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  batch_size: 64
  total_epochs: 4
  explorer_input:
    taskset:
      name: taskset
      storage_type: file
      path: ${oc.env:TRINITY_TASKSET_PATH}
      split: train
      subset_name: null
      format:
        prompt_key: messages
        response_key: action_truth
      rollout_args:
        temperature: 1.0
        logprobs: 0
    eval_tasksets: [ ]
    default_workflow_type: learn2ask_workflow
    default_reward_fn_type: math_reward
  trainer_input:
    experience_buffer:
      name: experience_buffer
      storage_type: queue
      enable_progress_bar: false
      path: ''
      replay_buffer:
        enable: true
        priority_fn: linear_decay
        priority_fn_args:
          decay: 0.1
explorer:
  runner_per_model: 32
  max_timeout: 900
  max_retry_times: 2
  rollout_model:
    engine_type: vllm_async
    engine_num: 4
    tensor_parallel_size: 1
    use_v1: true
    enforce_eager: true
    enable_prefix_caching: false
    enable_chunked_prefill: false
    gpu_memory_utilization: 0.9
    dtype: bfloat16
    seed: 42
    enable_thinking: false
    enable_openai_api: true
  auxiliary_models:
    - model_path: ${oc.env:TRINITY_AUX_MODEL_PATH,Qwen/Qwen2.5-32B-Instruct}
      engine_num: 1
      tensor_parallel_size: 2
      enable_thinking: false
      max_prompt_tokens: 2048
      max_response_tokens: 1024
  eval_interval: 10000
  bench_on_latest_checkpoint: false
trainer:
  trainer_type: verl
  save_interval: 90
  enable_preview: true
  grad_clip: 1.0
  trainer_config:
    actor_rollout_ref:
      hybrid_engine: true
      model:
        external_lib: null
        override_config: {}
        enable_gradient_checkpointing: true
        use_remove_padding: true
      actor:
        strategy: fsdp
        ppo_micro_batch_size_per_gpu: 4
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 4096
        ppo_epochs: 1
        shuffle: false
        ulysses_sequence_parallel_size: 1
        checkpoint:
          load_contents:
          - model
          - optimizer
          - extra
          save_contents:
          - model
          - optimizer
          - extra
        optim:
          lr: 5.0e-07
          lr_warmup_steps_ratio: 0.0
          warmup_style: constant
          total_training_steps: -1
        fsdp_config:
          wrap_policy:
            min_num_params: 0
          param_offload: false
          optimizer_offload: false
          fsdp_size: -1
      ref:
        fsdp_config:
          wrap_policy:
            min_num_params: 0
          param_offload: false
          optimizer_offload: false
          fsdp_size: -1
        log_prob_micro_batch_size_per_gpu: 8
        log_prob_use_dynamic_bsz: true
        log_prob_max_token_len_per_gpu: 4096
        ulysses_sequence_parallel_size: 1
    trainer:
      balance_batch: true
      resume_mode: auto
      resume_from_path: ''
      default_hdfs_dir: null
      remove_previous_ckpt_in_save: false
      del_local_ckpt_after_load: false
      val_before_train: false
      max_actor_ckpt_to_keep: null
      max_critic_ckpt_to_keep: null
monitor:
  monitor_type: wandb
synchronizer:
  sync_method: nccl
  sync_interval: 10
  sync_timeout: 7200
