data:
  # basic info
  dataset_path: /PATH/TO/DATASET/
  # dataset_config:
  train_split: train
  eval_split: test
  format_config:
    prompt_key: 'question'
    response_key: 'gt_answer'
  # db related
  db_url: ''
  # downstream loading related
  total_epoch: 20
  batch_size: 288
  default_workflow_type: 'math_workflow'
model:
  model_path: /PATH/TO/MODEL/
  max_prompt_tokens: 1024
  max_response_tokens: 3072
  checkpoint_path: /PATH/TO/CHECKPOINT/
  load_checkpoint: true
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  max_retry_times: 3
  max_retry_interval: 1
  train_dataset:
    name: math_buffer
    storage_type: queue
    algorithm_type: ppo
    path: 'sqlite:////math.db'
explorer:
  engine_type: vllm_async
  engine_num: 2
  runner_num: 32
  tensor_parallel_size: 1
  enable_prefix_caching: false
  enforce_eager: true
  dtype: bfloat16
  temperature: 1.0
  top_p: 1.0
  top_k: -1
  seed: 42
  logprobs: 0
  repeat_times: 8
  use_ray: false
  backend: 'nccl'
  max_pending_requests: 32
  max_waiting_steps: 4
synchronizer:
  sync_method: 'online'
  sync_iteration_interval: 2
trainer:
  trainer_type: 'verl'
  algorithm_type: ppo
  trainer_config_path: 'examples/grpo_math/train_math.yaml'
  sft_warmup_iteration: 0 # Set to integer to enable sft warmup
  eval_interval: 10
monitor:
  cache_root_dir: ""
  project: grpo_math
  name: grpo_math_example
