project: "mix_math"
name: "expert0.25_mu0.1"
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
algorithm:
  algorithm_type: mix
  repeat_times: 8
  sample_strategy_args:
    expert_data_ratio: 0.25
  policy_loss_fn_args:
    mu: 0.1
    clip_range: 0.2
    use_token_level_loss_in_sft: False
    use_dynamic_bsz: False
    repeat_times: 8
    ppo_mini_batch_size: 256
    ppo_micro_batch_size_per_gpu: 4
    ngpus_trainer: 4
    train_batch_size_expert: 64
    train_batch_size_usual: 192
model:
  model_path: /PATH/TO/MODEL/
  max_response_tokens: 10240
  max_model_len: 11264
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 40
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: math_train
      storage_type: file
      path: /PATH/TO/DATASET/
      split: 'train'
      format:
        prompt_key: 'problem'
        response_key: 'answer'
      rollout_args:
        temperature: 1.0
        logprobs: 0
    eval_tasksets:
    - name: math_eval
      storage_type: file
      path: /PATH/TO/DATASET/
      split: 'test'
      format:
        prompt_key: 'problem'
        response_key: 'answer'
    default_workflow_type: 'math_workflow'
  trainer_input:
    experience_buffer:
      name: math_buffer
      storage_type: queue
      path: /PATH/TO/BUFFER/
    sft_warmup_dataset:
      name: math_sft
      storage_type: file
      algorithm_type: sft
      path: /PATH/TO/EXPERT_DATA/
      split: 'train'
      format:
        prompt_type: messages
        messages_key: 'messages'
explorer:
  eval_interval: 10
  runner_num: 16
  rollout_model:
    engine_type: vllm_async
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 1
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/mix_math/train_mix_math.yaml'
  save_interval: 50
monitor:
  monitor_type: wandb
