data:
  total_epoch: 20
  batch_size: 96
  dataset_path: 'countdown_dataset/oneshot-split'
  default_workflow_type: 'math_workflow'
  train_split: 'train'
  eval_split: ''
  default_reward_fn_type: 'countdown_reward'
  format_config:
    prompt_key: 'question'
    response_key: 'answer'
model:
  model_path: '/PATH/TO/MODEL/CHECKPOINT/'
  max_prompt_tokens: 256
  max_response_tokens: 1024
  checkpoint_path: 'checkpoints/qwen2.5-1.5B-countdown'
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  max_retry_times: 3
  max_retry_interval: 1
  train_dataset:
    name: countdown_buffer
    storage_type: queue
    algorithm_type: ppo
    path: 'sqlite:////countdown.db'
explorer:
  engine_type: vllm_async
  engine_num: 2
  runner_num: 32
  tensor_parallel_size: 1
  enable_prefix_caching: false
  enforce_eager: true
  dtype: bfloat16
  temperature: 1.0
  top_p: 1.0
  top_k: -1
  seed: 42
  logprobs: 0
  repeat_times: 5
  use_ray: false
  backend: 'nccl'
  max_pending_requests: 32
  max_waiting_steps: 4
synchronizer:
  sync_method: 'online'
  sync_iteration_interval: 10
trainer:
  trainer_type: 'verl'
  algorithm_type: ppo
  trainer_config_path: 'examples/ppo_countdown/train_countdown.yaml'
  sft_warmup_iteration: 0
  eval_interval: 1000
monitor:
  cache_root_dir: ""
  project: "Trinity-RFT-countdown"
  name: "qwen2.5-1.5B-countdown"
