global_config:
  total_epochs: 20
  batch_size: 96
  eval_interval: 1000
  algorithm_type: ppo
model:
  model_path: '/PATH/TO/MODEL/CHECKPOINT/'
  max_prompt_tokens: 256
  max_response_tokens: 1024
  checkpoint_path: 'checkpoints/qwen2.5-1.5B-countdown'
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: countdown
      storage_type: file
      path: 'countdown_dataset/oneshot-split'
      format:
        prompt_key: 'question'
        response_key: 'answer'
      rollout_args:
        repeat_times: 5
        temperature: 1.0
        logprobs: 0
    default_workflow_type: 'math_workflow'
    default_reward_fn_type: 'countdown_reward'
  trainer_input:
    experience_buffer:
      name: countdown_buffer
      storage_type: queue
      path: 'sqlite:///countdown.db'
explorer:
  engine_type: vllm_async
  engine_num: 2
  runner_num: 32
  tensor_parallel_size: 1
  enable_prefix_caching: false
  enforce_eager: true
  dtype: bfloat16
  seed: 42
  use_ray: false
  backend: 'nccl'
  max_pending_requests: 32
  max_waiting_steps: 4
synchronizer:
  sync_method: 'nccl'
  sync_interval: 10
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/ppo_countdown/train_countdown.yaml'
  sft_warmup_steps: 0
  save_interval: 100
monitor:
  cache_root_dir: ""
  project: "Trinity-RFT-countdown"
  name: "qwen2.5-1.5B-countdown"
