project: "Trinity-RFT-gsm8k-experience-pipeline"
name: "qwen2.5-1.5B-gsm8k-experience-pipeline"
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
algorithm:
  algorithm_type: grpo
  repeat_times: 8
data_processor:
  data_processor_url: 'http://127.0.0.1:5005/data_processor'
  # experience pipeline related
  experience_pipeline:
    # I/O buffers
    input_buffers:
      - name: gsm8k_exp_output
    output_buffer:
      name: reshaped_gsm8k_exp_input
    # format mapping
    format:
      reward_key: 'reward'  # the key name of the reward in the experience
    # data active iterator related
    dj_config_path: 'examples/grpo_gsm8k_experience_pipeline/dj_scoring_exp.yaml'
    clean_strategy: 'iterative'
    # reward shaping
    reward_shaping:
      - stats_key: 'llm_quality_score'
        op_type: ADD
        weight: 1.0
model:
  model_path: /PATH/TO/MODEL/
  max_response_tokens: 1024
  max_model_len: 1280
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 96
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: gsm8k
      storage_type: file
      path: 'openai/gsm8k'
      subset_name: 'main'
      split: 'train'
      format:
        prompt_key: 'question'
        response_key: 'answer'
      rollout_args:
        temperature: 1.0
    eval_tasksets:
    - name: gsm8k-eval
      storage_type: file
      path: 'openai/gsm8k'
      subset_name: 'main'
      split: 'test'
      format:
        prompt_key: 'question'
        response_key: 'answer'
    default_workflow_type: 'math_workflow'
  explorer_output:
    name: gsm8k_exp_output
    storage_type: queue
    path: 'sqlite:///gsm8k_exp_output.db'
  trainer_input:
    experience_buffer:
      name: reshaped_gsm8k_exp_input
      storage_type: queue
      path: 'sqlite:///reshaped_gsm8k_exp_input.db'
explorer:
  eval_interval: 50
  runner_num: 32
  rollout_model:
    engine_type: vllm_async
    engine_num: 2
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 1
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_gsm8k_experience_pipeline/train_gsm8k.yaml'
  save_interval: 100
